jwt:
  secretKey: ${SECRET_KEY}

  access:
    expiration: 1800000 # 30분 (1000L(ms -> s) * 60L(s -> m) * 30L(m -> h))
    header: Authorization

  refresh:
    expiration: 86400000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
