spring:
  datasource:
    url: jdbc:mariadb://59.23.234.233:3306/brewing_business?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${MariaDB_PW}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul # 한국 시간대 설정
        format_sql: true  # SQL 포맷을 쉽게 보기 위해 true로 변경
        show_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none # validate, create 등 필요에 따라 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  config:
    activate:
      on-profile: local
    import:
      - application-jwt.yaml
springdoc:
  api-docs:
    path: '/api-docs'
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'
  swagger-ui:
    operations-sorter: 'alpha'
    tags-sorter: 'alpha'
    path: '/swagger-ui.html'
    disable-swagger-default-url: true
    doc-expansion: 'none'
  paths-to-match: '/**'